export const MAKE_OPTIONS = [
  { value: "Abarth", label: "Abarth" },
  { value: "Acura", label: "Acura" },
  { value: "Alfa_Romeo", label: "Alfa Romeo" },
  { value: "Aston_Martin", label: "Aston Martin" },
  { value: "Audi", label: "Audi" },
  { value: "Bentley", label: "Bentley" },
  { value: "BMW", label: "BMW" },
  { value: "Bugatti", label: "Bugatti" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Citroën", label: "Citroën" },
  { value: "Dacia", label: "Dacia" },
  { value: "Daewoo", label: "Daewoo" },
  { value: "Daihatsu", label: "Daihatsu" },
  { value: "Dodge", label: "Dodge" },
  { value: "Donkervoort", label: "Donkervoort" },
  { value: "DS", label: "DS" },
  { value: "Ferrari", label: "Ferrari" },
  { value: "Fiat", label: "Fiat" },
  { value: "Fisker", label: "Fisker" },
  { value: "Ford", label: "Ford" },
  { value: "Honda", label: "Honda" },
  { value: "Hummer", label: "Hummer" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Iveco", label: "Iveco" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Kia", label: "Kia" },
  { value: "KTM", label: "KTM" },
  { value: "Lada", label: "Lada" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Lancia", label: "Lancia" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Landwind", label: "Landwind" },
  { value: "Lexus", label: "Lexus" },
  { value: "Lotus", label: "Lotus" },
  { value: "Maserati", label: "Maserati" },
  { value: "Maybach", label: "Maybach" },
  { value: "Mazda", label: "Mazda" },
  { value: "McLaren", label: "McLaren" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "MG", label: "MG" },
  { value: "Mini", label: "Mini" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Morgan", label: "Morgan" },
  { value: "Nissan", label: "Nissan" },
  { value: "Opel", label: "Opel" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Porsche", label: "Porsche" },
  { value: "Renault", label: "Renault" },
  { value: "Rolls-Royce", label: "Rolls-Royce" },
  { value: "Rover", label: "Rover" },
  { value: "Saab", label: "Saab" },
  { value: "Seat", label: "Seat" },
  { value: "Skoda", label: "Skoda" },
  { value: "Smart", label: "Smart" },
  { value: "SsangYong", label: "SsangYong" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Volvo", label: "Volvo" },
]

export const SERVICE_OPTIONS = [
  { value: "Brakes", label: "Brakes" },
  { value: "Suspension", label: "Suspension" },
  { value: "Alignment", label: "Alignment" },
  { value: "Exhaust", label: "Exhaust" },
  { value: "Air_Conditioning", label: "Air Conditioning" },
  { value: "Tire_sale", label: "Tire sale" },
  { value: "Tire_repair", label: "Tire repair" },
  { value: "Road_Force_balancing", label: "Road Force balancing" },
  { value: "TPMS_programming", label: "TPMS programming" },
  { value: "Diagnostics", label: "Diagnostics" },
  { value: "Electrical", label: "Electrical" },
  { value: "Emissions", label: "Emissions" },
  { value: "Hybrid_car_service", label: "Hybrid car service" },
  { value: "Engine_replacement", label: "Engine replacement" },
  { value: "Transmission_replacement", label: "Transmission replacement" },
  { value: "Pre-purchase_inspection", label: "Pre-purchase inspection" },
  { value: "Dripless_undercoating", label: "Dripless undercoating" },
]
